image: docker:24.0.2

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test

build_and_run:
  stage: test
  tags:
    - self-hosted
  before_script:
    - apk add --no-cache bash docker-cli-compose
  script:
    - ./build_and_run.sh
  rules:
    # Run every day at 6am via GitLab pipeline schedule
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    # Run for merge requests to enforce CI before merging
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
