name: CI

on:
  pull_request:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.scontain.com
          username: "cicd-group"
          password: ${{ secrets.CICD_PULL_TOKEN }}
      - name: Run build_and_run.sh
        run: |
          chmod +x build_and_run.sh
          ./build_and_run.sh

  dependabot-automerge:
    needs: test
    runs-on: self-hosted
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge Dependabot PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
